apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: smokeping
resources:
  - pvc.yaml
  - deploy.yaml
  - svc.yaml
  - ing.yaml
configMapGenerator:
- name: smokeping-config
  files:
    - etc/more-targets.sh
